import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "ress";
import { css } from "@emotion/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={{ minWidth: "1024px" }} className={inter.className}>
        {children}
      </body>
    </html>
  );
}
